/*
    Cameron Martin,
    Jared Key,
    Christopher Duong,
    Luke Higginbotham
*/
package ded;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFCell;
import java.io.FileInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;

public class LoginPageUI extends javax.swing.JFrame {

    HomePageUI homePage;
    
    /**
     * Creates new form LoginPageUI
     */
    public LoginPageUI() {
        initComponents();
        homePage = new HomePageUI(this);
    }
    
    public void complyWithSettings(boolean isDark, float fontSize) {
        if(isDark) {
            loginPanel.setBackground(new Color((float) 0.09803921568,(float) 0.09803921568,(float) 0.43921568627));
        }
        else {
            loginPanel.setBackground(new Color((float) 0.50196078431, (float) 0.50196078431, (float) 0.50196078431));
        }
        errorLbl.setFont(errorLbl.getFont().deriveFont(fontSize));
        loginBtn.setFont(loginBtn.getFont().deriveFont(fontSize));
        passLbl.setFont(passLbl.getFont().deriveFont(fontSize));
        userLbl.setFont(userLbl.getFont().deriveFont(fontSize));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        passwordInput = new javax.swing.JPasswordField();
        usernameInput = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        logoLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database for the Eternally Deceased");

        passwordInput.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        usernameInput.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        loginBtn.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setAlignmentX(0.5F);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        errorLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));

        logoLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLbl.setText("DED");

        userLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userLbl.setText("Username:");

        passLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passLbl.setText("Password:");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(userLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(passLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)))
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameInput)
                    .addComponent(loginBtn)
                    .addComponent(errorLbl)
                    .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordInput, usernameInput});

        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(errorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(loginBtn)
                .addGap(60, 60, 60))
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordInput, usernameInput});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        try{ 
            boolean correctUser = false;
            int i = 2;
            FileInputStream file = new FileInputStream(new File("C:/Users/Chris/Documents/NetBeansProjects/DED/src/ded/UserLogins.xlsx"));
            XSSFWorkbook wb;
            wb = new XSSFWorkbook(file);
            XSSFSheet sheet;
            sheet = wb.getSheetAt(0);
            XSSFRow row = sheet.getRow(i);
            XSSFCell cell = row.getCell(1);
            while(i < sheet.getLastRowNum()) {
                if(usernameInput.getText().equals(cell.toString())) { // Update to check if valid username
                    correctUser = true;
                    cell = row.getCell(2);
                    if(passwordInput.getText().equals(cell.toString())) { // Update to check if correct password
                        homePage.setCurUserAndCem(row.getCell(0).toString(),sheet.getRow(0).getCell(0).toString());
                        homePage.updateWelcome();
                        homePage.setVisible(true);
                        this.setVisible(false);
                        errorLbl.setText("");
                    }
                    else {
                        
                        errorLbl.setText("Incorrect Password");
                    }
                    break;
                }
                else {
                    i++;
                    row = sheet.getRow(i);
                    cell = row.getCell(1);
                    
                }
            }
            
            if(!correctUser) errorLbl.setText("Invalid Username");
            this.passwordInput.setText("");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginPageUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPageUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}